#!/usr/bin/env bash
# scripts/init-ssl.sh
# Obtain a Let's Encrypt TLS certificate using Certbot standalone mode.
# Run AFTER setup-vps.sh and BEFORE starting the production Docker stack.
#
# Usage: sudo bash scripts/init-ssl.sh
# Prerequisite: .env must be filled in with DOMAIN=your.domain.com
set -euo pipefail

RADIO_DIR="${RADIO_DIR:-/opt/radio}"

# Load .env to get the domain
if [[ -f "${RADIO_DIR}/.env" ]]; then
  # shellcheck disable=SC1090
  set -a; source "${RADIO_DIR}/.env"; set +a
else
  echo "ERROR: ${RADIO_DIR}/.env not found. Copy .env.example and fill in DOMAIN."
  exit 1
fi

if [[ -z "${DOMAIN:-}" ]]; then
  echo "ERROR: DOMAIN is not set in .env"
  exit 1
fi

SSL_DIR="${RADIO_DIR}/ssl"
CERTBOT_DIR="${RADIO_DIR}/certbot"

echo "==> Obtaining SSL certificate for ${DOMAIN}..."

# Install Certbot if missing
if ! command -v certbot &>/dev/null; then
  echo "Installing Certbot..."
  apt-get update -qq
  apt-get install -y -qq certbot
fi

# Stop Nginx if running (standalone mode needs port 80 free)
if docker compose -f "${RADIO_DIR}/docker-compose.prod.yml" ps nginx 2>/dev/null | grep -q "Up"; then
  echo "Stopping Nginx container temporarily..."
  docker compose -f "${RADIO_DIR}/docker-compose.prod.yml" stop nginx
  NGINX_WAS_RUNNING=1
else
  NGINX_WAS_RUNNING=0
fi

# Obtain certificate
certbot certonly \
  --standalone \
  --non-interactive \
  --agree-tos \
  --register-unsafely-without-email \
  -d "${DOMAIN}" \
  --cert-path "${CERTBOT_DIR}/live/${DOMAIN}/cert.pem" \
  --key-path  "${CERTBOT_DIR}/live/${DOMAIN}/privkey.pem" \
  --fullchain-path "${CERTBOT_DIR}/live/${DOMAIN}/fullchain.pem" \
  --config-dir "${CERTBOT_DIR}"

# Create ssl/ symlinks for Nginx to read
mkdir -p "${SSL_DIR}"
ln -sf "${CERTBOT_DIR}/live/${DOMAIN}/fullchain.pem" "${SSL_DIR}/fullchain.pem"
ln -sf "${CERTBOT_DIR}/live/${DOMAIN}/privkey.pem"   "${SSL_DIR}/privkey.pem"

echo "Certificate obtained and linked at ${SSL_DIR}/"

# Write production Nginx SSL config
cat > "${RADIO_DIR}/config/nginx-ssl.conf" <<NGINXSSL
# nginx-ssl.conf — generated by init-ssl.sh for ${DOMAIN}
# Included by docker-compose.prod.yml Nginx service

server {
    listen 80;
    server_name ${DOMAIN};
    # Redirect all HTTP to HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    # Stream proxy (rate limited)
    location /stream/ {
        limit_req zone=stream burst=20 nodelay;
        proxy_pass         http://icecast/;
        proxy_buffering    off;
        proxy_cache        off;
        chunked_transfer_encoding on;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location /stream/admin { return 403; }

    location /api/ {
        limit_req zone=api burst=60 nodelay;
        proxy_pass         http://api/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
    }

    location /broadcast {
        proxy_pass         http://api/broadcast;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_read_timeout 3600s;
    }

    location / {
        proxy_pass         http://web/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}
NGINXSSL

echo "SSL Nginx config written to ${RADIO_DIR}/config/nginx-ssl.conf"

# Set up Certbot auto-renewal cron
CRON_JOB="0 3 * * * certbot renew --quiet --deploy-hook 'docker compose -f ${RADIO_DIR}/docker-compose.prod.yml exec -T nginx nginx -s reload'"
(crontab -l 2>/dev/null | grep -v "certbot renew"; echo "${CRON_JOB}") | crontab -
echo "Auto-renewal cron job installed."

# Restart Nginx if we stopped it
if [[ "${NGINX_WAS_RUNNING}" == "1" ]]; then
  echo "Restarting Nginx..."
  docker compose -f "${RADIO_DIR}/docker-compose.prod.yml" start nginx
fi

echo ""
echo "✅  SSL setup complete for ${DOMAIN}"
echo ""
echo "Next step: docker compose -f ${RADIO_DIR}/docker-compose.prod.yml up -d"
